-- MySQL Script generated by MySQL Workbench
-- Tue Aug 22 09:23:49 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema common_backend
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `common_backend` ;

-- -----------------------------------------------------
-- Schema common_backend
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `common_backend` DEFAULT CHARACTER SET utf8 ;
USE `common_backend` ;

-- -----------------------------------------------------
-- Table `common_backend`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `common_backend`.`user` ;

CREATE TABLE IF NOT EXISTS `common_backend`.`user` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(64) NULL,
  `password` CHAR(60) NULL,
  `email` VARCHAR(128) NULL,
  `mobile` VARCHAR(16) NULL,
  `status` TINYINT(4) NULL DEFAULT 1 COMMENT '0:未生效账号；1:已生效账号',
  `identity` TINYINT(4) NULL DEFAULT 0 COMMENT '0:未认证用户;1:已认证个人用户;2:已认证企业用户',
  `token` VARCHAR(255) NULL COMMENT '登录令牌',
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `common_backend`.`common_backend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `common_backend`.`common_backend` ;

CREATE TABLE IF NOT EXISTS `common_backend`.`common_backend` (
  `id` BIGINT(20) NOT NULL,
  `userId` BIGINT(20) NOT NULL,
  `common_backendNo` VARCHAR(128) NULL COMMENT '合同编号',
  `common_backendDocFile` VARCHAR(128) NULL COMMENT '合同文件存储位置',
  `title` VARCHAR(255) NULL COMMENT '合同标题',
  `signType` TINYINT(4) NULL DEFAULT 1 COMMENT '1:无序签，2：顺序签，3：无序签',
  `signMethod` TINYINT(4) NULL DEFAULT 1 COMMENT '1:用户个人名义签署；2:企业公章名义签署',
  `payMethod` TINYINT(4) NULL DEFAULT 1 COMMENT '付费方式：1:我承担全部费用；2:签收方各自承担',
  `signData` TEXT NULL COMMENT '签名数字电文',
  `userName` VARCHAR(64) NULL COMMENT '合同创建人名称',
  `startedAt` DATETIME NULL COMMENT '签署开始日期',
  `endedAt` DATETIME NULL COMMENT '签署结束日期',
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '合同文档';


-- -----------------------------------------------------
-- Table `common_backend`.`sign_process`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `common_backend`.`sign_process` ;

CREATE TABLE IF NOT EXISTS `common_backend`.`sign_process` (
  `id` BIGINT(20) NOT NULL,
  `userId` BIGINT(20) UNSIGNED NOT NULL,
  `common_backendId` BIGINT NOT NULL,
  `signPlatform` VARCHAR(32) NOT NULL COMMENT '签署平台，电脑端，手机端',
  `createdAt` DATETIME NOT NULL COMMENT '签署日期',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '签名人';


-- -----------------------------------------------------
-- Table `common_backend`.`common_backend_doc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `common_backend`.`common_backend_doc` ;

CREATE TABLE IF NOT EXISTS `common_backend`.`contract_doc` (
  `id` BIGINT(20) NOT NULL,
  `userId` BIGINT(20) NOT NULL,
  `common_backendId` BIGINT(20) NOT NULL,
  `doc` VARCHAR(128) NULL COMMENT '文档存储位置',
  `fileName` VARCHAR(255) NULL,
  `fileType` VARCHAR(8) NULL COMMENT '文件类型，pdf，docx，',
  `fileSize` BIGINT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '合同文件';


-- -----------------------------------------------------
-- Table `common_backend`.`inner_message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `common_backend`.`inner_message` ;

CREATE TABLE IF NOT EXISTS `common_backend`.`inner_message` (
  `id` BIGINT(20) NOT NULL,
  `message` VARCHAR(255) NOT NULL,
  `isAll` TINYINT NOT NULL COMMENT '1:向所有用户发消息;0:不向所有用户发',
  `createdAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `common_backend`.`message_box`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `common_backend`.`message_box` ;

CREATE TABLE IF NOT EXISTS `common_backend`.`message_box` (
  `id` BIGINT(20) NOT NULL,
  `userId` BIGINT(20) NOT NULL,
  `msgId` BIGINT(20) NOT NULL,
  `isRead` TINYINT NOT NULL COMMENT '0:未读；1:已读',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `common_backend`.`contact_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `common_backend`.`contact_list` ;

CREATE TABLE IF NOT EXISTS `common_backend`.`contact_list` (
  `id` BIGINT(20) NOT NULL,
  `userId` BIGINT(20) UNSIGNED NOT NULL COMMENT '所属用户id',
  `contactId` BIGINT(20) UNSIGNED NOT NULL COMMENT '联系人id',
  `createdAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `common_backend`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `common_backend`.`contact` ;

CREATE TABLE IF NOT EXISTS `common_backend`.`contact` (
  `id` BIGINT(20) NOT NULL,
  `userId` BIGINT(20) NOT NULL,
  `common_backendId` BIGINT(20) UNSIGNED NOT NULL COMMENT '合同id',
  `contactListId` BIGINT(20) NOT NULL COMMENT '联系人id',
  `realName` VARCHAR(64) NULL COMMENT '真实名称',
  `mobile` VARCHAR(16) NULL,
  `userName` VARCHAR(64) NULL COMMENT '用户名称',
  `createdat` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '联系人';


-- -----------------------------------------------------
-- Table `common_backend`.`sign_code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `common_backend`.`sign_code` ;

CREATE TABLE IF NOT EXISTS `common_backend`.`sign_code` (
  `id` BIGINT(20) NOT NULL,
  `userId` BIGINT(20) NOT NULL,
  `title` VARCHAR(128) NOT NULL,
  `signPic` VARCHAR(128) NOT NULL,
  `status` TINYINT(4) UNSIGNED NULL DEFAULT 1 COMMENT '签名状态：1:正式的；0:打草稿的',
  `createdAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '用户的签名或者公章';


-- -----------------------------------------------------
-- Table `common_backend`.`common_backend_sign_code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `common_backend`.`common_backend_sign_code` ;

CREATE TABLE IF NOT EXISTS `common_backend`.`contract_sign_code` (
  `common_backendId` BIGINT(20) UNSIGNED NOT NULL,
  `signCodeId` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`common_backendId`, `signCodeId`))
ENGINE = InnoDB
COMMENT = '签名code';


-- -----------------------------------------------------
-- Table `common_backend`.`province`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `common_backend`.`province` ;

CREATE TABLE IF NOT EXISTS `common_backend`.`province` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(6) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `common_backend`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `common_backend`.`city` ;

CREATE TABLE IF NOT EXISTS `common_backend`.`city` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(6) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `provincecode` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `common_backend`.`area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `common_backend`.`area` ;

CREATE TABLE IF NOT EXISTS `common_backend`.`area` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(6) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `citycode` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `common_backend`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `common_backend`.`company` ;

CREATE TABLE IF NOT EXISTS `common_backend`.`company` (
  `id` BIGINT(20) NOT NULL,
  `userId` BIGINT(20) UNSIGNED NOT NULL,
  `name` VARCHAR(128) NULL COMMENT '企业名称',
  `code` VARCHAR(128) NULL COMMENT '三证合一编码',
  `provinceCode` VARCHAR(6) NULL COMMENT '企业所在省编码',
  `cityCode` VARCHAR(6) NULL COMMENT '企业所在市编码',
  `areaCode` VARCHAR(6) NULL COMMENT '企业所在区编码',
  `address` VARCHAR(255) NULL COMMENT '企业详细地址',
  `licensePhoto` VARCHAR(255) NULL COMMENT '企业营业执照照片',
  `checkPhoto` VARCHAR(255) NULL COMMENT '验证申请表\n',
  `checkTemplate` VARCHAR(255) NULL COMMENT '申请表模板',
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `common_backend`.`user_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `common_backend`.`user_info` ;

CREATE TABLE IF NOT EXISTS `common_backend`.`user_info` (
  `id` BIGINT(20) UNSIGNED NOT NULL,
  `userId` BIGINT(20) UNSIGNED NOT NULL,
  `sex` TINYINT(1) NULL DEFAULT 1 COMMENT '性别，0:女；1:男',
  `nationality` VARCHAR(45) NULL COMMENT '名族',
  `bornAt` DATETIME NULL COMMENT '出生日期',
  `provinceCode` VARCHAR(6) NULL COMMENT '省份编码\n',
  `cityCode` VARCHAR(6) NULL COMMENT '市镇编码',
  `areaCode` VARCHAR(6) NULL COMMENT '乡村编码',
  `address` VARCHAR(255) NULL COMMENT '详细街道\n',
  `identityCode` VARCHAR(128) NULL COMMENT '身份证号码',
  `identityPhoto` VARCHAR(255) NULL COMMENT '身份证照片',
  `handIdentityPhoto` VARCHAR(255) NULL COMMENT '手持身份证照片',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '用户信息表';


/*表结构插入*/
DROP TABLE IF EXISTS `sys_permission`;

CREATE TABLE `sys_permission` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `url` varchar(256) DEFAULT NULL COMMENT 'url地址',
  `name` varchar(64) DEFAULT NULL COMMENT 'url描述',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `sys_role` */

DROP TABLE IF EXISTS `sys_role`;

CREATE TABLE `sys_role` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(32) DEFAULT NULL COMMENT '角色名称',
  `type` varchar(10) DEFAULT NULL COMMENT '角色类型',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `sys_role_permission` */

DROP TABLE IF EXISTS `sys_role_permission`;

CREATE TABLE `sys_role_permission` (
  `rid` bigint(20) DEFAULT NULL COMMENT '角色ID',
  `pid` bigint(20) DEFAULT NULL COMMENT '权限ID'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `sys_admin` */

DROP TABLE IF EXISTS `sys_admin`;

CREATE TABLE `sys_admin` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `username` varchar(20) DEFAULT NULL COMMENT '用户昵称',
  `email` varchar(128) DEFAULT NULL COMMENT '邮箱|登录帐号',
  `password` char(60) DEFAULT NULL COMMENT '密码',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `last_login_time` datetime DEFAULT NULL COMMENT '最后登录时间',
  `status` tinyint(1) DEFAULT '1' COMMENT '1:有效，0:禁止登录',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `sys_admin_role` */

DROP TABLE IF EXISTS `sys_admin_role`;

CREATE TABLE `sys_admin_role` (
  `uid` bigint(20) DEFAULT NULL COMMENT '用户ID',
  `rid` bigint(20) DEFAULT NULL COMMENT '角色ID'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
